services:
  - type: web
    name: prateleira-app
    env: docker
    plan: free

    dockerfilePath: ./Dockerfile

    envVars:
      - key: DB_URL
        fromDatabase:
          name: prateleira-db
          property: connectionString

      - key: DB_USERNAME
        value: myuser

      - key: DB_PASSWORD
        value: secret

      - key: JWT_SECRET
        sync: false

      - key: JWT_EXPIRATION
        sync: false

      - key: MAIL_HOST
        sync: false

      - key: MAIL_PORT
        sync: false

      - key: MAIL_USERNAME
        sync: false

      - key: MAIL_PASSWORD
        sync: false

databases:
  - name: prateleira-db
    plan: free